#! /bin/sh

bspc -r "*"

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_radius 6
bspc config top_padding 8
bspc config bottom_padding 0
bspc config border_width 4
bspc config focused_border_color "#33ff00"
bspc config window_gap 16
bspc config focus_follows_pointer true
bspc config honor_size hints false
bspc config initial_polarity second_child
bspc config automatic_scheme alternate

bspc rule -a mpv state=pseudo_tiled
bspc rule -a Sxiv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Deadbeef desktop=^9
bspc rule -a Gimp desktop=^6 follow=on

bspc config split_ratio 0.42
