#! /bin/sh

bspc -r "*"

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width 4
bspc config window_gap 16
bspc config focus_follows_pointer true

bspc config split_ratio 0.4
bspc rule -a xterm state=floating
