#! /bin/sh

bspc -r "*"

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width 4
bspc config focused_border_color "#33ff00"
bspc config window_gap 24
bspc config focus_follows_pointer true
bspc config honor_size hints true

bspc config split_ratio 0.45
