#!/usr/bin/env ksh
# ksh is usually a symlink to oksh, loksh, mksh, or ksh93

# Prompt
export PS1="\e[0;31m{\e[0;33m\w\e[1;31m}\e[0;32m\s\e[0;37m[\e[1;34m\#\e[0;37m]\n \e[0;35m\$(printf '\U000003bc')\e[0;36m "
export PS4="\e[1;32m[\e[1;34m\u\e[1;35m@\e[1;31m\$(printf '\U000003bc')\e[1;32m] \e[0;33m\$(printf '\U000003bb')\e[0;36m "

# Aliases
alias q="exit"
alias a="exit"
alias z="exit"
alias d="doas"
alias r="busybox clear"
alias k="busybox killall"
alias l="exa -alhHF"
alias lb="lsblk"
alias h="man"
alias hk="apropos"
alias t="tldr"
alias y="cheat"
alias m="doas mount"
alias u="doas umount -R /mnt"
alias e="busybox echo"
alias c="mdcat"
alias b="busybux tar -xvf"
alias j="$PAGER"
alias f="grep"
alias n="busybox wc -l"
alias i="openbsd-file"
alias s="/opt/bin/sed"
alias w="whereis"
alias v="nvim"
alias V="doas nvim"
alias x="xbps-query -S"
alias xl="xbps-query -l"
alias xs="xbps-query -Rs"
alias xx="xbps-query -x"
alias X="xbps-query -X"
alias xi="doas xbps-install -Su"
alias xr="doas xbps-remove -R"
alias xo="doas xbps-remove -O"
alias W="torsocks -i wget -r"
alias g="git clone"
alias p="git pull"
alias ga="git add --all"
alias gc="git commit -m"
alias gp="git push -u origin master"
alias gb="git branch"
alias gm="git merge"
alias gs="git status"
alias gw="git switch"
alias gh="git checkout"
alias M="bmake && doas bmake install && bmake clean"
alias pgrep="busybox pgrep"
alias cat="busybox cat"
