require('vis')
require('cursors')

vis.events.subscribe(vis.events.INIT, function()
        vis:command('set autoindent on')
        vis:command('set expandtab true')
        vis:command('set tabwidth 8')
        vis:command('set theme based')
        vis:command('set syntax on')
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
        vis:command('set number')
        vis:command('set relativenumber')
        vis:command('set cursorline on')
end)
