require('vis')
-- require('surround')
-- require('vis-commentary')

vis.events.subscribe(vis.events.INIT, function()
        vis:command('set autoindent on')
        vis:command('set expandtab true')
        vis:command('set tabwidth 8')
        vis:command('set theme based')
        vis:command('set cursorline on')
        vis:command('set syntax on')
        vis:command('filetype plugin indent on')
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
        vis:command('set number')
        vis:command('set relativenumber')
end)
