fish_vi_key_bindings
fish_vi_cursor

abbr v 'nvim'
abbr vi 'nvim ~/.config/i3/config'
abbr vb 'nvim ~/.config/i3blocks/config'
abbr vf 'nvim ~/.config/fish/config.fish'
abbr vn 'nvim ~/.config/nvim/init.vim'
abbr vv 'nvim ~/.config/vifm/vifmrc'
abbr vp 'nvim ~/.profile'
abbr vx 'nvim ~/.Xresources'
abbr vh 'nvim ~/scripts/browser/HOME.html'

abbr q 'exit'
abbr s 'sudo'
abbr r 'clear'
abbr b 'bash'
abbr k 'kill all'
abbr l 'less'
abbr m 'man'
abbr M 'sudo mount'
abbr U 'sudo umount -R /mnt'
abbr i 'touch'
abbr e 'echo'
abbr a 'cat -E'
abbr f 'grep'
abbr d 'sed'
abbr lb 'lsblk'
abbr z 'unzip'
abbr ss 'ssh -X'
abbr n 'wc -l'

abbr xi 'sudo xbps-install -Su'
abbr xu 'sudo xbps-remove -R'
abbr xx 'sudo xbps-src'
abbr x 'xbps-query -Rs'
abbr xs 'xbps-query -S'
abbr xl 'xbps-query -l | wc -l'
abbr w 'wget'

abbr g 'git clone'
abbr G 'git pull'
abbr ga 'git add --all'
abbr gc 'git commit -m'
abbr gp 'git push -u origin master'
abbr gb 'git branch'
abbr gm 'git merge'
abbr gC 'git checkout'
abbr gs 'git status'

abbr c 'tcc -run'
abbr j 'julia'
abbr rr 'Rscript --vanilla'
abbr o 'node'
abbr t 'latex'
abbr T 'pdflatex'
abbr S 'sent show'
